import React, { useState, useEffect } from 'react';
import { NationalReportItem } from '../../types/nationalAdmin';
import {
  FileSpreadsheet,
  FileText,
  Download,
  PlusCircle,
  CheckCircle2,
  Calendar,
  Layers,
  FileDown,
} from 'lucide-react';

export const AnalyticsReportsTab: React.FC = () => {
  const [reports, setReports] = useState<NationalReportItem[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [generateModalOpen, setGenerateModalOpen] = useState(false);
  const [newTitle, setNewTitle] = useState('');
  const [newReportType, setNewReportType] = useState('NATIONAL_DILRMP');
  const [newScope, setNewScope] = useState('All India (National)');
  const [newFormat, setNewFormat] = useState('PDF');
  const [notice, setNotice] = useState('');

  useEffect(() => {
    fetchReports();
  }, []);

  const fetchReports = async () => {
    setIsLoading(true);
    try {
      const res = await fetch('/api/admin/reports');
      const data = await res.json();
      if (data.success) {
        setReports(data.reports);
      }
    } catch (err) {
      console.error('Failed to load reports:', err);
    } finally {
      setIsLoading(false);
    }
  };

  const handleGenerateReport = async (e: React.FormEvent) => {
    e.preventDefault();
    try {
      const res = await fetch('/api/admin/reports/generate', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          title: newTitle,
          reportType: newReportType,
          scope: newScope,
          fileFormat: newFormat,
        }),
      });
      const data = await res.json();
      if (data.success) {
        setNotice(`Report "${data.report.title}" generated successfully with NIC digital signature.`);
        setGenerateModalOpen(false);
        setNewTitle('');
        fetchReports();
        setTimeout(() => setNotice(''), 4000);
      }
    } catch (err) {
      console.error('Failed to generate report:', err);
    }
  };

  const handleDownload = (rep: NationalReportItem) => {
    // Simulated instant file download
    const dummyContent = `GOVERNMENT OF INDIA\nMINISTRY OF RURAL DEVELOPMENT & NIC\n\nOfficial Cadastral Report: ${rep.title}\nScope: ${rep.scope}\nGenerated By: ${rep.generatedBy}\nTimestamp: ${rep.generatedAt}\nVerification Status: DIGITAL EMBEDDED SHA-256 SIGNATURE VALID\n\nTotal Parcels Analyzed: 38,80,00,000\nDigitized & Verified: 89.7%\nCompliance: DILRMP / SVAMITVA Guidelines 2026.`;
    const blob = new Blob([dummyContent], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${rep.title.replace(/\s+/g, '_')}.${rep.fileFormat.toLowerCase()}`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="space-y-6">
      {/* Top Banner */}
      <div className="bg-white border border-gray-300 p-4 rounded shadow-sm flex flex-col md:flex-row items-start md:items-center justify-between gap-4">
        <div>
          <div className="flex items-center gap-2">
            <span className="text-xs font-bold px-2 py-0.5 rounded bg-blue-100 text-[#123A78]">
              STATUTORY REPORTING ENGINE
            </span>
            <span className="text-xs text-gray-500 font-semibold">MoRD & Parliamentary Submissions</span>
          </div>
          <h2 className="text-xl font-extrabold text-gray-900 mt-1 flex items-center gap-2">
            <FileSpreadsheet className="w-6 h-6 text-[#123A78]" />
            National Cadastral Analytics & Official Report Dispatches
          </h2>
          <p className="text-xs text-gray-600">
            DILRMP digitization audits, state compliance scorecards, and district mutation SLA reports
          </p>
        </div>

        <button
          onClick={() => setGenerateModalOpen(true)}
          className="px-3.5 py-2 bg-[#123A78] hover:bg-[#0E2C5B] text-white rounded text-xs font-bold flex items-center gap-1.5 shadow-sm transition"
        >
          <PlusCircle className="w-4 h-4" />
          Generate New Statutory Report
        </button>
      </div>

      {notice && (
        <div className="p-3 bg-green-50 border border-green-200 text-green-800 text-xs rounded font-medium flex items-center gap-2">
          <CheckCircle2 className="w-4 h-4 text-[#0B7A3B]" />
          {notice}
        </div>
      )}

      {/* Reports Catalog */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        {reports.map((rep) => (
          <div
            key={rep.id}
            className="bg-white border border-gray-300 rounded shadow-sm p-4 hover:border-[#123A78] transition flex flex-col justify-between"
          >
            <div>
              <div className="flex items-start justify-between gap-2 mb-2">
                <span className="px-2 py-0.5 rounded bg-blue-50 text-[#123A78] border border-blue-200 font-bold text-[10px]">
                  {rep.reportType}
                </span>
                <span className="text-xs font-bold px-1.5 py-0.5 bg-gray-100 rounded text-gray-700">
                  {rep.fileFormat} • {(rep.fileSizeBytes / 1000000).toFixed(1)} MB
                </span>
              </div>

              <h4 className="text-sm font-bold text-gray-900 leading-snug">{rep.title}</h4>
              <p className="text-xs text-gray-500 mt-1">Scope: {rep.scope}</p>
            </div>

            <div className="mt-4 pt-3 border-t border-gray-200 flex items-center justify-between text-xs">
              <div className="text-[11px] text-gray-500">
                <span>By: {rep.generatedBy}</span>
                <span className="block font-mono">
                  {new Date(rep.generatedAt).toLocaleDateString()}
                </span>
              </div>

              <button
                onClick={() => handleDownload(rep)}
                className="px-3 py-1.5 bg-[#123A78] hover:bg-[#0E2C5B] text-white rounded text-xs font-bold transition flex items-center gap-1.5 shadow-sm"
              >
                <FileDown className="w-3.5 h-3.5" />
                Download {rep.fileFormat}
              </button>
            </div>
          </div>
        ))}
      </div>

      {/* Generate Report Modal */}
      {generateModalOpen && (
        <div className="fixed inset-0 bg-black/50 z-50 flex items-center justify-center p-4">
          <div className="bg-white rounded max-w-md w-full border border-gray-300 shadow-xl overflow-hidden">
            <div className="p-4 bg-[#123A78] text-white flex items-center justify-between">
              <h3 className="text-sm font-bold flex items-center gap-2">
                <PlusCircle className="w-4 h-4" />
                Compile Official Statutory Report
              </h3>
              <button
                onClick={() => setGenerateModalOpen(false)}
                className="text-white hover:text-gray-200 text-sm font-bold"
              >
                ✕
              </button>
            </div>

            <form onSubmit={handleGenerateReport} className="p-4 space-y-3 text-xs">
              <div>
                <label className="block font-bold text-gray-700 mb-1">Report Title</label>
                <input
                  type="text"
                  required
                  placeholder="e.g. Q3 2026 SVAMITVA Cadastral Survey & Resettlement Audit"
                  value={newTitle}
                  onChange={(e) => setNewTitle(e.target.value)}
                  className="w-full p-2 border border-gray-300 rounded focus:outline-none focus:border-[#123A78]"
                />
              </div>

              <div>
                <label className="block font-bold text-gray-700 mb-1">Report Category</label>
                <select
                  value={newReportType}
                  onChange={(e) => setNewReportType(e.target.value)}
                  className="w-full p-2 border border-gray-300 rounded focus:outline-none focus:border-[#123A78]"
                >
                  <option value="NATIONAL_DILRMP">National DILRMP Digitization</option>
                  <option value="STATE_EXECUTIVE">State Cadastral Executive</option>
                  <option value="DISTRICT_PERFORMANCE">District Collector SLA Performance</option>
                  <option value="FRAUD_FORENSICS">Fraud Forensic & Tamper Trends</option>
                  <option value="GIS_CADASTRAL">ISRO Satellite Land Use Monitoring</option>
                </select>
              </div>

              <div className="grid grid-cols-2 gap-3">
                <div>
                  <label className="block font-bold text-gray-700 mb-1">Geographic Scope</label>
                  <input
                    type="text"
                    required
                    value={newScope}
                    onChange={(e) => setNewScope(e.target.value)}
                    className="w-full p-2 border border-gray-300 rounded focus:outline-none focus:border-[#123A78]"
                  />
                </div>
                <div>
                  <label className="block font-bold text-gray-700 mb-1">Export Format</label>
                  <select
                    value={newFormat}
                    onChange={(e) => setNewFormat(e.target.value)}
                    className="w-full p-2 border border-gray-300 rounded focus:outline-none focus:border-[#123A78]"
                  >
                    <option value="PDF">PDF (Digital Seal Encrypted)</option>
                    <option value="EXCEL">Microsoft Excel (.xlsx)</option>
                    <option value="CSV">Standard CSV Data Dump</option>
                  </select>
                </div>
              </div>

              <div className="flex justify-end gap-2 pt-2 border-t border-gray-200">
                <button
                  type="button"
                  onClick={() => setGenerateModalOpen(false)}
                  className="px-3 py-1.5 border border-gray-300 text-gray-700 font-bold rounded hover:bg-gray-50"
                >
                  Cancel
                </button>
                <button
                  type="submit"
                  className="px-4 py-1.5 bg-[#123A78] hover:bg-[#0E2C5B] text-white font-bold rounded"
                >
                  Compile & Digitally Sign
                </button>
              </div>
            </form>
          </div>
        </div>
      )}
    </div>
  );
};
